version: '3.8'

services:

  redis:
    image: redis:alpine
    restart: always
    container_name: my_postgres
    environment:
      - POSTGRES_PASSWORD=1
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pg_data:

# docker-compose build   (image)
# docker-compose up      (container)

# docker-compose down
# docker-compose down -v

# dvdrental
#
# docker rm my_postgres
# stop
# remove
